inherit: true

build:
    environment:
        php:
            version: 5.5.12
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer: true
    php_changetracking: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
