build:

    environment:
        php:
            version: "5.5.12" # Common versions: 5.4.28, 5.5.12, or hhvm
            ini:
                'date.timezone': 'UTC'
        #elasticsearch: false

    dependencies:
        before:
            #- mysql -uroot -e 'CREATE DATABASE phalcon'
            #- composer install --prefer-dist -o
            #- git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
            #- cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n'  /home/scrutinizer/.phpenv/versions/5.5.12/etc/php.ini
            #- php -m | grep -i Phalcon

filter:
    paths: [src/*]
    excluded_paths: [build/*, phpunit/*, vendor/*]

tools:
    php_sim: true
    php_pdepend:
        enabled: true
        command: pdepend
        suffixes:
            - php
        excluded_dirs:
            - vendor
            - phpunit

    #php_code_coverage: true

    php_analyzer:
        enabled: true
        filter:
            excluded_paths: [build/*, phpunit/*, vendor/*]
        extensions:
            - php

    sensiolabs_security_checker: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        extensions:
            - php
        command: phpcs
        filter:
           excluded_paths: [build/*, phpunit/*, vendor/*]

    php_cs_fixer:
        enabled: true
        extensions:
            - php
        command: php-cs-fixer
        config:
            level: all

checks:
    php:
        code_rating: true
        duplication: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        use_statement_alias_conflict: true
        symfony_request_injection: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        require_php_tag_first: true
        precedence_in_conditions: true
        precedence_mistakes: true
        parameter_non_unique: true
        no_eval: true
        no_non_implemented_abstract_methods: true
        no_duplicate_arguments: true
        missing_arguments: true
        instanceof_class_exists: true
        foreach_traversable: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        argument_type_checks: true
        assignment_of_null_return: true
        useless_calls: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        too_many_arguments: true
        switch_fallthrough_commented: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        php5_style_constructor: true
        phpunit_assertions: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_function_call_in_for_loop: true
        no_unnecessary_final_modifier: true
        no_property_on_interface: true
        method_calls_on_non_object: true
        foreach_usable_as_reference: true
        fix_use_statements:
            remove_unused: false
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        encourage_shallow_comparison: true
        deprecated_code_usage: true
        avoid_unnecessary_concatenation: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true