inherit: true

build:

    environment:
        php:
            version: "5.5.12" # Common versions: 5.4.28, 5.5.12, or hhvm
            ini:
                'date.timezone': 'UTC'
                'extension=phalcon.so' : ''
        elasticsearch: false
        redis: false

    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE phalcon_searcher'
            - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
            - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install
            - composer self-update
            - composer install --prefer-dist -o

    tests:
        before:
                - 'bundle exec rspec'
                - 'phpunit'

        override:
                -
                    command: vendor/bin/phpunit --configuration ./build/travis-ci.xml --coverage-clover=coverage.clover
                    coverage:
                        file: coverage.clover
                        format: php-clover

filter:
    paths: [src/*]
    excluded_paths: [build/*, phpunit/*]

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_coverage: true