build:
    environment:
        php:
            version: 5.5.12
        mysql: true
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
        
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer: true
    php_changetracking: true
    sensiolabs_security_checker: true        
    
checks:
    php:
        code_rating: true
        duplication: true
