# Required to run your project under the correct environment.
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:

  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6

# omitting "script:" will default to phpunit
before_script:
  - composer self-update
  - phpenv rehash
  - composer install --dev --no-interaction -o
  - sh ./build/install.sh

script:
  - phpunit --configuration ./phpunit/phpunit.xml --coverage-clover=clover.xml

after_script:
  - php vendor/bin/coveralls -v